### ISSUE TITLE
support helm repo add

### ISSUE THREAD

**Issue by willzhang** [seaweedfs/seaweedfs-operator#105]
support helm repo add, like this
```
$ helm repo add seaweedfs-operator https://seaweedfs.github.io/seaweedfs-operator/helm
Error: looks like "https://seaweedfs.github.io/seaweedfs-operator/helm" is not a valid chart repository or cannot be reached: failed to fetch https://seaweedfs.github.io/seaweedfs-operator/helm/index.yaml : 404 Not Found
```

**Comment by egg82** [comment]
Mostly resolved by #97 (and I tested a few minutes ago)
```
helm repo add seaweedfs-operator https://seaweedfs.github.io/seaweedfs-operator/helm
helm template  seaweedfs-operator seaweedfs-operator/seaweedfs-operator
```

Note that a few values had to change:
1. `image.tag` needed to be set to `1.0.2` - the default `0.0.1` will never work, as the image of that version is actually `v0.0.1` (and also is two years old)
2. `webhook.enabled` needed to be set to `false` as the "cert" secret isn't created (I'm assuming it uses `cert-manager`, but that part doesn't seem to be working) - NOTE: `seaweedfs-operator-create-webhook-certificates-xxx` does spin up later and seems to create the secret, so after disabling this I suppose you can re-enable it. A `seaweedfs-operator-patch-mutating-webhook-xxx` is also created which seems to fail in a CrashLoopBackOff state. I assume re-enabling the webhook would resolve this but I don't know for sure
3. `serviceMonitor.enabled` needed to be set to `false` as it required the `ServiceMonitor` CRD which I don't have

Here's my FluxCD config, in a directory called `seaweedfs-operator`:

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - seaweedfs-operator-namespace.yaml
  - seaweedfs-operator-helmrepository.yaml
  - seaweedfs-operator-helmrelease.yaml
```

seaweedfs-operator-namespace.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs-operator
```

seaweedfs-operator-helmrepository.yaml
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs-operator/helm
```

seaweedfs-operator-helmrelease.yaml
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: seaweedfs-operator
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-operator
        namespace: seaweedfs-operator
  values:
    webhook:
      enabled: false
    serviceMonitor:
      enabled: false
    image:
      tag: "1.0.2"
```
