### ISSUE TITLE
Is there a way to set the configuration for security.toml via the operator?

### ISSUE THREAD

**Issue by jjaferson** [seaweedfs/seaweedfs-operator#106]
I was trying to create the security.toml file and configure it via the operator but I don't see an option for it.

https://github.com/seaweedfs/seaweedfs/wiki/Security-Configuration

**Comment by chrislusf** [comment]
This is supported now — since **v1.0.12** the operator provisions SeaweedFS's `security.toml` for you rather than requiring you to hand-write it.

Enable mTLS across all gRPC endpoints via `spec.tls` on the `Seaweed` CR:

```yaml
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
spec:
  tls:
    enabled: true
    # optional — reference an existing cert-manager Issuer/ClusterIssuer.
    # Omit to let the operator provision a self-signed Issuer + CA chain
    # owned by the CR (matches the Helm chart default).
    # issuerRef:
    #   name: my-issuer
    #   kind: ClusterIssuer
```

With cert-manager installed, the operator provisions the cert chain and renders a `security.toml` ConfigMap with `[grpc.master]`, `[grpc.filer]`, `[grpc.volume]`, … sections pointing every component at the mounted certs.

JWT signing keys (`jwt.filer_signing.key`) are rendered automatically whenever a filer or admin server is in the spec — no TLS required for that part.

Closing as resolved. Please reopen if you need a knob this doesn't cover (e.g. supplying a fully custom `security.toml`).
