### ISSUE TITLE
Not able to create Seaweed instance via Operator

### ISSUE THREAD

**Issue by nitisht** [seaweedfs/seaweedfs-operator#62]
Installation on current master fails with error in filer 

```
➜ kubectl get pods
NAME                READY   STATUS             RESTARTS   AGE
seaweed1-filer-0    0/1     CrashLoopBackOff   6          9m43s
seaweed1-master-0   1/1     Running            1          9m47s
seaweed1-volume-0   1/1     Running            0          9m43s
```

```
➜ kubectl logs seaweed1-filer-0
flag provided but not defined: -peers
Example: weed filer -port=8888 -master=<ip:port>[,<ip:port>]*
```

Steps followed:

1. ➜ make install
2. ➜ make deploy
3. 
```
seaweedfs-operator on  master [?] via 🐹 v1.15.2 using ☁️  default/
➜ kubectl apply -f seaweed_v1_seaweed.yaml
seaweed.seaweed.seaweedfs.com/seaweed1 created
```

```yaml
➜ cat seaweed_v1_seaweed.yaml
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
  namespace: default
spec:
  # Add fields here
  image: chrislusf/seaweedfs:3.02
  volumeServerDiskCount: 1
  hostSuffix: seaweed.abcdefg.com
  master:
    replicas: 1
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 1
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
```
