### ISSUE TITLE
controller-gen file missing and missing required field in io.k8s.api.admissionregistration.v1.MutatingWebhook

### ISSUE THREAD

**Issue by rkmsk** [seaweedfs/seaweedfs-operator#75]
I've stumbled across 2 issues:

1) I had to manually do `go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0` otherwise I got an error
```
<my home>/go/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/bin/sh: <my home>/go/bin/controller-gen: No such file or directory
make: *** [manifests] Error 127
```

2) There is a bug in `seaweedfs-operator/config/webhook/manifests.yaml` where 
```
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
```
is missing for 
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
```
thus showing an error on `make deploy`
