### ISSUE TITLE
Publish Helm Charts

### ISSUE THREAD

**Issue by XAMPPRocky** [seaweedfs/seaweedfs-operator#79]
Hello, first of all, thank you to @Programmeris for contributing a helm chart to the operator to help make this project easier to deploy on Kubernetes. It would be nice if that work could be continued upon to publish chart releases, so that adding Seaweedfs to a project can be as simple as adding the following to your helmfile. This will require setting up CI/CD to publish new helm packages on releases, either to something like https://artifacthub.io or to a GitHub Pages repository in the `seaweedfs` organisation.

```yaml
repositories:
 - name: seaweedfs
   url: https://seaweedfs.github.io/charts

releases:
- name: seaweed-operator
  namespace: seaweedfs
  chart: seaweedfs/operator
```
